### ISSUE TITLE
technicality - customers don't have first & last names

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-one-to-many-and-many-to-many-joins-lab#1]
Directions are:

_Return a dataframe with all of the customers' first and last names along with details for each of their order numbers, order dates, and statuses._

but the customers are businesses and only have customerName - it is the customer contact which has first and last names.

Directions should be something like:

_Return a dataframe with all of the customer contacts (first and last name) along with details for each of the customers' order numbers, order dates, and statuses._

Similarly for all of the directions below.

**Comment by climatebrad** [comment]
Similarly for 

_Return a dataframe with all of the customers' first and last names along with details for each of their order numbers, order dates, and statuses._

**Comment by sumedh10** [comment]
Thanks for reporting this, it's fixed.
